export const STORE = {
  name: "허브 스토어",
  banners: [
    {
      id: "b1",
      title: "배너1",
      subtitle: "인기 미니게임 팩 할인!",
      image: "https://images.unsplash.com/photo-1606813907291-d86efa9b1f0c?auto=format&fit=crop&w=1200&q=80",
      link: "./product.html?id=p1",
      active: true,
    },
    {
      id: "b2",
      title: "배너2",
      subtitle: "신규 서버팩 출시",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
      link: "./seller.html?id=s1",
      active: true,
    },
  ],
  sellers: [
    {
      id: "s1",
      name: "GodDot Gaming",
      desc: "미니게임/서버팩 전문",
      avatar: "https://api.dicebear.com/8.x/shapes/svg?seed=godot",
      verified: true,
      recommended: true,
    },
    {
      id: "s2",
      name: "MC 관리자",
      desc: "공식 상품/이벤트",
      avatar: "https://api.dicebear.com/8.x/shapes/svg?seed=admin",
      verified: true,
      recommended: false,
    },
  ],
  products: [
    {
      id: "p1",
      sellerId: "s1",
      title: "마인크래프트 TNT 러시안룰렛 미니게임",
      priceKrw: 30000,
      version: "1.21.1",
      tags: ["미니게임", "컨텐츠"],
      thumb: "https://images.unsplash.com/photo-1627855437693-3df1b1dfe3c7?auto=format&fit=crop&w=1000&q=80",
      published: true,
      createdAt: "2025-12-01",
      images: [
        "https://images.unsplash.com/photo-1627855437693-3df1b1dfe3c7?auto=format&fit=crop&w=1200&q=80",
      ],
      desc: "TNT 러시안룰렛 미니게임 서버팩. 간단 설치, 빠른 진행, 재미 보장.",
    },
    {
      id: "p2",
      sellerId: "s1",
      title: "RPG 인생역할 초고퀄 디방 서버팩",
      priceKrw: 35000,
      version: "1.12.2",
      tags: ["서버팩", "RPG"],
      thumb: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
      published: true,
      createdAt: "2025-11-20",
      images: [],
      desc: "직업/퀘스트/던전 포함 RPG 서버팩.",
    },
  ],
};
